### ISSUE TITLE
great app!

### ISSUE THREAD

**Issue by forer11** [amit-schwartz-u/rooMe#123]
Loved the app and total design, although i had 2 issues:
1. google sign in didn't work for me
2. the app crashed when i used the pixel 2 emulator, i think it has something to do with the background settings, as i had a similar issue once. i can figure it out for you if you like me to.

**Comment by ShaharBirzon** [comment]
1. we are currently working on this issue.
2. Im still not sure what happend here, we would like you to try and figure it out if you can.
thank you!
