### ISSUE TITLE
feedback for open-source calss

### ISSUE THREAD

**Issue by iporat08** [amit-schwartz-u/rooMe#124]
hey,
The app looks great but on my samsung  A7 device it crashes after one swipe.
I undertstand it doesn't happen on every device, so maybe the problem is with my device.

Good luck! :)

**Comment by ShaharBirzon** [comment]
hey i would love if you can check if it still happens as I'm not sure why.

**Comment by amit-schwartz-u** [comment]
it probably happened because he tried using the app while we deleted the users from the firebase. that's normally the reason for this type of crash.
