### ISSUE TITLE
Profile names titles

### ISSUE THREAD

**Issue by mormoshe** [amit-schwartz-u/rooMe#148]
Hey,
In the profile settings the names titles were cut, so I can see only "First" and "Last".
Maybe it's because of the phone resolution.
![WhatsApp Image 2020-06-24 at 17 18 48](https://user-images.githubusercontent.com/40175415/85574286-4ed50680-b63f-11ea-9fce-cc445dcc43b9.jpeg)

**Comment by ShaharBirzon** [comment]
we had a small mistake with the constraints.. now it's fixed!
