### ISSUE TITLE
Suggestion: add a log out option

### ISSUE THREAD

**Issue by mormoshe** [amit-schwartz-u/rooMe#149]
Hey, I think it will be a useful to add a log out option somewhere in the application.
Also, if someone has previously searched for an apartment and is now looking for a roomate, I think they should have the option to do so (I couldn't find a way).

**Comment by ShaharBirzon** [comment]
furtunately, someone contributed a piece of code that allows the user to delete his account after finish using the app. You are more than welcome to try this and let us know if it works as expected.
