### ISSUE TITLE
Suggestion: add a third gender option

### ISSUE THREAD

**Issue by iporat08** [amit-schwartz-u/rooMe#153]
Hey,
I've noticed that when editing a profile, the user should choose "gentleman" or "lady" as gender.
I think it could make some potential users uncomfortable...
How about adding another option? Something like "Non-binary/ third gender"?

Good luck,

Ido

**Comment by ShaharBirzon** [comment]
thats a good idea! thank you

**Comment by ShaharBirzon** [comment]
done.
