### ISSUE TITLE
BUG - When running the app for the second time it doesn't work 

### ISSUE THREAD

**Issue by carmelLevy** [amit-schwartz-u/rooMe#155]
Hi, 
I tried running your app from my Android Studio and at the second time the following happened:
![image](https://user-images.githubusercontent.com/50371133/85788638-f896bf00-b735-11ea-97e4-ebd8a6d9804a.png)

**Comment by ShaharBirzon** [comment]
yes we are aware, there are problems with some emulators. We truly recommend to run the app on an actual android phone.. it always works better :)
thank you!
