### ISSUE TITLE
Suggestion - Add a UI explaining the user he can't pick entering date in the past

### ISSUE THREAD

**Issue by carmelLevy** [amit-schwartz-u/rooMe#161]
Hi, 
I tried entering an "entering date" with the year 2010 for instance, and it let me. 
I think that a user can accsidently enter illegal year and then he won't understand why he can't find any roomates/apartments. 
I would suggest you to pop a dialog explaining the user that he can't choose illegal dates. 
![image](https://user-images.githubusercontent.com/50371133/85792248-dc961c00-b73b-11ea-8e4e-974b91f63ac8.png)

**Comment by MaxGoldgamer** [comment]
As time machines are yet to exist, this is a good suggestion, thank you!

**Comment by ShaharBirzon** [comment]
fixed! thank you
