### ISSUE TITLE
Bug in app's flow 

### ISSUE THREAD

**Issue by carmelLevy** [amit-schwartz-u/rooMe#164]
Hi, 
After I pick on the main screen the option for searching an apartment I can't figure out how to go back to the main screen. 
When I try pressing the back button it gets out of the app and I didn't found any button that brings you back to the main screen.
I suggest you add a "Home" button", so the user won't have to log out of the app in order to search for a roomate instead of an apartment.

**Comment by ShaharBirzon** [comment]
You are right! therefore we have a logout option now, so if the user get confused, he can log out and choose a different user. 
Thanks!
