### ISSUE TITLE
Suggestion: Organize your code in meaningful directories structure

### ISSUE THREAD

**Issue by asaf-kali** [amit-schwartz-u/rooMe#170]
First - nice project!
My suggestion is not product-related, but code related. Take a look at the code scturcture:
![image](https://user-images.githubusercontent.com/28392088/85904860-7e883800-b812-11ea-866e-1453944ffe19.png)
It would be much easier both for you and for somone new joining the project, if the classes were organized into directories with short and meaningful names.
Preferably, the basic models would sit in one directory, activities in another, and fragments or adapters divided into some  catagorised folder structure.
A good thumb rule can be to organise it such that no folder contains more then 5 classes.

**Comment by asaf-kali** [comment]
Maybe something like that:
![image](https://user-images.githubusercontent.com/28392088/85905502-3e29b980-b814-11ea-9927-ea00734fa89f.png)

Of couse this needs more thinking from someone who really knows the project, but it's a nice start.
It is also always good to seperate the models the application uses, it's logical parts, and it's actual views implementation (from a quick look in the code, im not sure which class is which, but you guys will probably do it quickly).

**Comment by ShaharBirzon** [comment]
that's a great idea, we actually didn't organize it that well. We are planning to take your advice about that, with small differences of naming and hierarchy. 
Thank you!

**Comment by ShaharBirzon** [comment]
done!
